

import { FamilyMember, RelationType, Post, SupportTicket } from './types';

export const MOCK_USER_ID = 'user-1';

export const COMMON_PROFESSIONS = [
  "Software Engineer", "Doctor", "Architect", "Teacher", "Business Owner", 
  "Lawyer", "Accountant", "Artist", "Civil Servant", "Military Service",
  "Consultant", "Data Scientist", "Pharmacist", "Chef", "Writer",
  "Investment Banker", "Pilot", "Nurse", "Student", "Homemaker"
];

export const COMMON_RELIGIONS = [
  "Hindu", "Muslim", "Christian", "Sikh", "Jain", "Buddhist", "Parsi", "Jewish", "Other"
];

export const COMMON_CASTES = [
  "Brahmin", "Kshatriya", "Vaishya", "Shudra", "Jat", "Rajput", "Kayastha", "Maratha", "Reddy", "Kamma", "Nair", "Vanniyar", "Gounder", "Iyer", "Iyengar"
];

export const COMMON_SUBCASTES = [
  "Kanyakubja", "Saryuparin", "Gaur", "Saraswat", "Chitpavan", "Deshastha", "Vadama", "Vathima", "Brihacharanam", "Ashtasahasram"
];

export const COMMON_LOCATIONS = [
  "New York, USA", "London, UK", "Dubai, UAE", "Singapore", "Sydney, Australia",
  "Toronto, Canada", "Berlin, Germany", "Paris, France", "Tokyo, Japan",
  "Mumbai, India", "Bengaluru, India", "Delhi, India", "Chennai, India", 
  "California, USA", "Texas, USA", "Melbourne, Australia", "Zurich, Switzerland"
];

export const INITIAL_FAMILY: Record<string, FamilyMember> = {
  'user-1': {
    id: 'user-1',
    name: 'Arjun Sharma',
    relation: RelationType.SELF,
    gender: 'Male',
    dob: '1990-05-15',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    gothra: 'Bharadwaj',
    location: 'Bengaluru, India',
    avatarUrl: 'https://picsum.photos/seed/arjun/200/200',
    isMarried: true,
    spouseId: 'spouse-1',
    parentIds: ['father-1', 'mother-1'],
    childrenIds: ['child-1'],
    joined: true,
    profession: 'Software Engineer',
    bio: 'Tech enthusiast and family man.',
    email: 'arjun@example.com',
    phoneNumber: '+919876543210',
    status: 'active',
    role: 'admin' // Granting Admin Access
  },
  'spouse-1': {
    id: 'spouse-1',
    name: 'Priya Sharma',
    relation: RelationType.SPOUSE,
    gender: 'Female',
    dob: '1992-08-20',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Saryuparin',
    gothra: 'Kashyap',
    location: 'Bengaluru, India',
    avatarUrl: 'https://picsum.photos/seed/priya/200/200',
    isMarried: true,
    spouseId: 'user-1',
    parentIds: ['priya-dad', 'priya-mom'],
    childrenIds: ['child-1'],
    joined: true,
    profession: 'Architect',
    email: 'priya@example.com',
    phoneNumber: '+919876543211',
    status: 'active'
  },
  'father-1': {
    id: 'father-1',
    name: 'Ramesh Sharma',
    relation: RelationType.FATHER,
    gender: 'Male',
    dob: '1960-01-10',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    gothra: 'Bharadwaj',
    avatarUrl: 'https://picsum.photos/seed/ramesh/200/200',
    isMarried: true,
    spouseId: 'mother-1',
    parentIds: ['grandpa-1', 'grandma-1'],
    childrenIds: ['user-1', 'sibling-1'],
    joined: false,
    createdBy: 'user-1',
    profession: 'Retired Civil Servant',
    location: 'Delhi, India',
  },
  'mother-1': {
    id: 'mother-1',
    name: 'Sunita Sharma',
    relation: RelationType.MOTHER,
    gender: 'Female',
    dob: '1965-03-15',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/sunita/200/200',
    isMarried: true,
    spouseId: 'father-1',
    parentIds: ['maternal-grandpa-1', 'maternal-grandma-1'],
    childrenIds: ['user-1', 'sibling-1'],
    joined: false,
    createdBy: 'user-1',
    profession: 'Homemaker',
    location: 'Delhi, India',
  },
  'grandpa-1': {
    id: 'grandpa-1',
    name: 'Harish Sharma',
    relation: RelationType.GRANDFATHER,
    gender: 'Male',
    dob: '1935-04-20',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/harish/200/200',
    isMarried: true,
    spouseId: 'grandma-1',
    parentIds: [],
    childrenIds: ['father-1', 'uncle-1'],
    joined: false,
    createdBy: 'user-1',
    profession: 'Farmer',
    location: 'Varanasi, India',
  },
  'grandma-1': {
    id: 'grandma-1',
    name: 'Gayatri Devi',
    relation: RelationType.GRANDMOTHER,
    gender: 'Female',
    dob: '1940-06-10',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/gayatri/200/200',
    isMarried: true,
    spouseId: 'grandpa-1',
    parentIds: [],
    childrenIds: ['father-1', 'uncle-1'],
    joined: false,
    createdBy: 'user-1',
    profession: 'Homemaker',
    location: 'Varanasi, India',
  },
  'uncle-1': {
    id: 'uncle-1',
    name: 'Suresh Sharma',
    relation: RelationType.UNCLE, // Paternal Uncle
    gender: 'Male',
    dob: '1962-08-15',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/suresh/200/200',
    isMarried: false,
    parentIds: ['grandpa-1', 'grandma-1'],
    childrenIds: [],
    joined: false,
    createdBy: 'user-1',
    profession: 'Doctor',
    location: 'Lucknow, India',
  },
  'sibling-1': {
    id: 'sibling-1',
    name: 'Amit Sharma',
    relation: RelationType.SIBLING,
    gender: 'Male',
    dob: '1995-11-30',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/amit/200/200',
    isMarried: false,
    spouseId: undefined,
    parentIds: ['father-1', 'mother-1'],
    childrenIds: [],
    joined: true,
    location: 'Mumbai, India',
    profession: 'Investment Banker',
    education: 'MBA, IIM',
    expectations: 'Looking for a professional partner with similar values.',
    email: 'amit.sharma@example.com',
    status: 'active'
  },
  'child-1': {
    id: 'child-1',
    name: 'Rohan Sharma',
    relation: RelationType.CHILD,
    gender: 'Male',
    dob: '2018-06-01',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/rohan/200/200',
    isMarried: false,
    parentIds: ['user-1', 'spouse-1'],
    childrenIds: [],
    joined: false,
    createdBy: 'user-1',
    location: 'Bengaluru, India',
  },
  // --- Sunita's (Mother) Side ---
  'maternal-grandpa-1': {
    id: 'maternal-grandpa-1',
    name: 'Anil Pandey',
    relation: RelationType.GRANDFATHER,
    gender: 'Male',
    dob: '1938-02-15',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/anil/200/200',
    isMarried: true,
    spouseId: 'maternal-grandma-1',
    parentIds: [],
    childrenIds: ['mother-1', 'sunita-bro-1', 'sunita-sis-1'],
    joined: false,
    createdBy: 'user-1', // Assuming Arjun added these
    profession: 'Professor',
    location: 'Kanpur, India',
  },
  'maternal-grandma-1': {
    id: 'maternal-grandma-1',
    name: 'Meera Pandey',
    relation: RelationType.GRANDMOTHER,
    gender: 'Female',
    dob: '1942-07-22',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/meera/200/200',
    isMarried: true,
    spouseId: 'maternal-grandpa-1',
    parentIds: [],
    childrenIds: ['mother-1', 'sunita-bro-1', 'sunita-sis-1'],
    joined: false,
    createdBy: 'user-1',
    profession: 'Teacher',
    location: 'Kanpur, India',
  },
  'sunita-bro-1': {
    id: 'sunita-bro-1',
    name: 'Rajesh Pandey',
    relation: RelationType.UNCLE, // Maternal Uncle (Mama)
    gender: 'Male',
    dob: '1968-04-10',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/rajesh/200/200',
    isMarried: false,
    parentIds: ['maternal-grandpa-1', 'maternal-grandma-1'],
    childrenIds: [],
    joined: false,
    createdBy: 'user-1',
    profession: 'Business Owner',
    location: 'Kanpur, India',
  },
  'sunita-sis-1': {
    id: 'sunita-sis-1',
    name: 'Sneha Pandey',
    relation: RelationType.AUNT, // Maternal Aunt (Masi)
    gender: 'Female',
    dob: '1972-09-05',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Kanyakubja',
    avatarUrl: 'https://picsum.photos/seed/sneha/200/200',
    isMarried: false,
    parentIds: ['maternal-grandpa-1', 'maternal-grandma-1'],
    childrenIds: [],
    joined: false,
    createdBy: 'user-1',
    profession: 'Designer',
    location: 'Lucknow, India',
  },
  
  // --- Priya's (Spouse) Side ---
  // These are createdBy 'spouse-1' (Priya), so Arjun (user-1) sees them as In-laws
  'priya-dad': {
    id: 'priya-dad',
    name: 'Vikram Shukla',
    relation: RelationType.FATHER_IN_LAW,
    gender: 'Male',
    dob: '1962-05-20',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Saryuparin',
    avatarUrl: 'https://picsum.photos/seed/vikram/200/200',
    isMarried: true,
    spouseId: 'priya-mom',
    parentIds: [],
    childrenIds: ['spouse-1', 'priya-bro'],
    joined: false,
    createdBy: 'spouse-1', 
    profession: 'Advocate',
    location: 'Jaipur, India',
  },
  'priya-mom': {
    id: 'priya-mom',
    name: 'Anjali Shukla',
    relation: RelationType.MOTHER_IN_LAW,
    gender: 'Female',
    dob: '1965-08-12',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Saryuparin',
    avatarUrl: 'https://picsum.photos/seed/anjali/200/200',
    isMarried: true,
    spouseId: 'priya-dad',
    parentIds: [],
    childrenIds: ['spouse-1', 'priya-bro'],
    joined: false,
    createdBy: 'spouse-1',
    profession: 'Artist',
    location: 'Jaipur, India',
  },
  'priya-bro': {
    id: 'priya-bro',
    name: 'Rahul Shukla',
    relation: RelationType.BROTHER_IN_LAW,
    gender: 'Male',
    dob: '1995-11-15',
    religion: 'Hindu',
    caste: 'Brahmin',
    subcaste: 'Saryuparin',
    avatarUrl: 'https://picsum.photos/seed/rahul/200/200',
    isMarried: false,
    parentIds: ['priya-dad', 'priya-mom'],
    childrenIds: [],
    joined: false,
    createdBy: 'spouse-1',
    profession: 'Software Developer',
    location: 'Pune, India',
  },
};

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    authorId: 'spouse-1',
    content: 'Family gathering at the annual Diwali celebration! So good to see everyone together. #Family #Diwali',
    imageUrl: 'https://picsum.photos/seed/diwali/600/400',
    likes: 24,
    comments: 2,
    timestamp: '2 hours ago',
    type: 'memory',
    privacy: 'public',
    commentsList: [
      { id: 'c1', authorId: 'sibling-1', content: 'Missed you all! Looks amazing.', timestamp: '1 hour ago' },
      { id: 'c2', authorId: 'mother-1', content: 'It was a blessed day.', timestamp: '30 mins ago' }
    ]
  },
  {
    id: 'post-2',
    authorId: 'sibling-1',
    content: 'Just got promoted to Senior Associate! Hard work pays off.',
    likes: 45,
    comments: 12,
    timestamp: '5 hours ago',
    type: 'milestone',
    privacy: 'public',
    commentsList: []
  },
  {
    id: 'post-3',
    authorId: 'uncle-1',
    content: 'Annual Family Summer Reunion in Jaipur. Please RSVP by next week!',
    likes: 12,
    comments: 4,
    timestamp: '1 day ago',
    type: 'invitation',
    privacy: 'extended',
    rsvpStatus: 'pending',
    pollOptions: []
  },
  {
    id: 'post-4',
    authorId: 'mother-1',
    content: 'Remember to book your tickets for Cousin Riya\'s wedding before prices go up!',
    likes: 5,
    comments: 1,
    timestamp: '3 hours ago',
    type: 'reminder',
    privacy: 'public'
  },
  {
    id: 'post-5',
    authorId: 'father-1',
    content: 'Turning 65 this weekend! Grateful for this beautiful family.',
    likes: 50,
    comments: 20,
    timestamp: '1 day ago',
    type: 'birthday',
    privacy: 'public',
    isWished: false
  },
  {
      id: 'post-6',
      authorId: 'user-1',
      content: 'So happy to announce that we are expecting a baby in December! 👶',
      imageUrl: 'https://picsum.photos/seed/baby/600/400',
      likes: 102,
      comments: 45,
      timestamp: '1 week ago',
      type: 'milestone',
      privacy: 'public',
      commentsList: [
          { id: 'c3', authorId: 'mother-1', content: 'Best news ever! God bless.', timestamp: '6 days ago' },
          { id: 'c4', authorId: 'priya-mom', content: 'Cannot wait to become a grandmother!', timestamp: '6 days ago' }
      ]
  },
  // Admin Demo: A reported post
  {
      id: 'post-reported',
      authorId: 'child-1',
      content: 'I hate this family and I am running away! #Angry',
      likes: 0,
      comments: 0,
      timestamp: '10 mins ago',
      type: 'general',
      privacy: 'public',
      isReported: true,
      reportReason: 'Inappropriate behavior / Concern for safety'
  }
];

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: 't-1',
    userId: 'sibling-1',
    subject: 'Incorrect Relation',
    message: 'My profile shows me as a Cousin instead of Sibling. Please fix.',
    status: 'open',
    timestamp: '2 hours ago'
  },
  {
    id: 't-2',
    userId: 'spouse-1',
    subject: 'Photo Upload Issue',
    message: 'I cannot upload my new profile picture. It says "server error".',
    status: 'open',
    timestamp: '5 hours ago'
  },
  {
    id: 't-3',
    userId: 'uncle-1',
    subject: 'Reset Password',
    message: 'I forgot my password, please help.',
    status: 'resolved',
    timestamp: '1 day ago'
  }
];
